### PR TITLE
Save information that data were exported

### PR DESCRIPTION
**Pull request by scardinius**
Related to #157

### CODE REVIEW

**Comment by deepak-srivastava** [comment]
We need to make sure it doesn't break the site for civi versions before 5.8. At the moment export fails for earlier versions of civi with the error:
image
One solution could be providing default values for last 2 new argument in the export hook. That would also mean that the entity export methods don't action anything if component table or ids are missing.

**Comment by scardinius** [comment]
@deepak-srivastava I added checking of version. Those new variables are available from 5.8.0
https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_export/#availability

**Comment by deepak-srivastava** [comment]
@scardinius That won't fix it because number of arguments in gdpr_civicrm_export() differ - 4 vs 6, which is what php is complaining about.

**Comment by scardinius** [comment]
@deepak-srivastava ah, yes, you're right. Added

**Comment by deepak-srivastava** [comment]
Thanks @scardinius :+1:

**Pull request merged**
