### PR TITLE
Make extension translatable to another language

### PR DESCRIPTION
**Pull request by tbuytaer**
This makes the extension translatable to other languages.

### CODE REVIEW

**Comment by tbuytaer** [comment]
Since PR #19 has been merged, I have now also added the translation function to the strings relating to permissions.

**Comment by veda-consulting** [comment]
@tbuytaer We've made a bunch of changes/fixes since you made this and they've been merged into the master now. This PR has some conflicts now, if you can resolve ASAP we can get it into the next release, due tomorrow. Is that possible?

**Comment by tbuytaer** [comment]
OK, I think you should be able to merge this into your master now.

**Comment by tbuytaer** [comment]
PR #27 created 2 new conflicts so I also resolved those now.

**Pull request merged**
